[package]
name = "tcp-serial-redirect"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
nix = { version = "0.29.0", features = ["poll", "signal", "time"] }
poll = "0.0.0"
serialport = "4.3.0"
time = "0.3.36"
